FROM python:3.12-slim

WORKDIR /app

COPY service/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

COPY service/ ./service/
COPY database/ ./database/

EXPOSE 8001

CMD ["python", "-u", "service/ws/main.py"]
